parameters:
  - name: TEST_USER_PASSWORD
    type: string
  - name: BASE_URL
    type: string

jobs:

  - job: test
    displayName: Run Selenium Tests
    steps:

      - download: none
      
      - checkout: self

      - task: NodeTool@0
        displayName: 'Use Node version 16'
        inputs:
          versionSpec: 16.x

      - script: |
          npm ci
        displayName: "NPM Install"

      - script: |
          npm install selenium-webdriver --with-deps
        displayName: "Selenium Install"

      - script: |
          set BASE_URL=${{ parameters.BASE_URL }}
          set TEST_ACCOUNT_USERNAME=tbd
          set TEST_ACCOUNT_PASSWORD=tbd
          set CI=true
          set SELENIUM_JUNIT_OUTPUT_NAME=results.xml
          npx mocha test
        displayName: "Run Selenium Tests"
        continueOnError: true

      - task: ArchiveFiles@2
        displayName: 'Add mochawesome-report to Archive'
        inputs:
          rootFolderOrFile: '$(Pipeline.Workspace)/s/mochawesome-report/'
          archiveFile: '$(Agent.TempDirectory)/$(Build.BuildId)_$(System.JobAttempt)$(System.StageAttempt).zip'


      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifacts'
        inputs:
          targetPath: '$(Agent.TempDirectory)/$(Build.BuildId)_$(System.JobAttempt)$(System.StageAttempt).zip'
          artifact: pipeline-artifacts

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '$(Pipeline.Workspace)/s/results.xml'
          testRunTitle: 'Selenium Tests Demo - $(System.StageName)'
        displayName: 'Publish Test Results'